on:
  push:
    branches:
      - master

jobs:
  build:
    container:
      image: rustlang/rust:nightly
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | bash - \
                && apt-get install -y nodejs
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build
          cd tuning_system-wasm
          wasm-pack build
          cd www
          npm install
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            tunning_system-wasm/www/dist/

      - name: Trigger Github Pages
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: update-playground
          repository: float3/float3.github.io
