on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21

      - name: install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -ssf | sh

      - name: checkout master
        uses: actions/checkout@v4.1.1
        with:
          ref: "master"

      - name: build
        run: |
          ./build_release.sh
          rm ./www/*LICENSE.txt
          rm ./www/styles.css
          mv ./www ./www-master
          git checkout -t origin/dev
          ./build.sh
          rm ./www/*LICENSE.txt
          rm ./www/styles.css
          mv ./www ./www-dev
          ls
          mv ./www-master ./www/
          mkdir -p ./www/dev
          mv ./www-dev/* ./www/dev/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "www"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
